trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type:       github
      ref:        main
      endpoint:   nivs-custom-devices
      name:       ni/niveristand-custom-device-build-tools

stages:
  - template: azure-templates/stages.yml@niveristand-custom-device-build-tools
    parameters:
      lvVersionsToBuild:
        - version: '2023'
          bitness: '64bit'
        - version: '2024'
          bitness: '64bit'
        - version: '2025'
          bitness: '64bit'

      buildSteps:
        - projectLocation: 'VeriStand Test Utilities.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'My Computer'
          buildSpec: 'SourceDistribution'

      releaseVersion: '25.0.0'
      buildOutputLocation: 'Built'
      archiveLocation: '\\nirvana\Measurements\VeriStandAddons\testing_tools'

      packages:
        - controlFileName: 'control'
          payloadMaps:
            - installLocation: 'ni-paths-LV$(lvVersion)DIR$(nipkgx64suffix)\vi.lib\NI\VeriStand Custom Device Testing Tools'
