[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\testing_tools'

[projects.utilities]
path = 'VeriStand Test Utilities.lvproj'

[[build.steps]]
name = 'Test Utilities'
type = 'lvBuildSpec'
project = '{utilities}'
target = 'My Computer'
build_spec = 'SourceDistribution'

[package]
type = 'nipkg'
payload_dir = 'Built'
install_destination = 'ni-paths-LV{veristand_version}DIR{nipaths_64_bitness_suffix}\vi.lib\NI\VeriStand Custom Device Testing Tools'
